version: '3.9'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    ports:
      - 80:80
    volumes:
      - /home/vagrant/webApp:/usr/share/nginx/html
