version: '3'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    ports:
      - 80:80
    volumes:
      - /nfs_shared/webApp:/usr/share/nginx/html/
  webserver:
    image: cipppo/webserver
    deploy: 
      replicas: 1
    volumes:
      - /home/vagrant/webserver/:/webserver

